blank_issues_enabled: false
contact_links:
  - name: Issue Tracker WDromi
    url: https://github.com/dromilang/dromi-web
    about: Usa l'issue tracker di WDromi, le issue per la documentazione non sono disponibili!
  - name: Dromi Issue Tracker
    url: https://github.com/dromilang/Dromi/issues
    about: Se riscontri problemi con Dromi usa l'issue tracker di Dromi.
